### ISSUE TITLE
Unable to install metamask for CMT in Chrome of Windows

### ISSUE THREAD

**Issue by shenzhun** [CyberMiles/travis-extension#1]
**Bug**
os: Windows 10
Chome: Version 70.0.3538.110

When we tried to install metamask by downloading the extension file from https://www.cybermiles.io/metamask/, even I could add the extension on my Chrome. But it shows that I can't use it because it is not downloaded from Chrome Store and there is no way to toggle it on. 

However, I found that if I modified the dowloaded file type to .zip, then used winrar to unzip it and loaded the uncompressed file onto Chrome. It worked finally.

**Expected behavior**
Because there are different ways to install this extension, I think the installation guide could add more detailed information about Windows and Macos. It will be better if we could download from the Chrome Store directly.

**Comment by maggie-wang-bbt** [comment]
Here is a link in stackoverflow.com, explains how to [install chrome extension not in the Chrome Web Store(for Windows) ](https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store).

Also we have submitted the extension to Chrome Web Store, waiting for Google to review. Will keep you posted on the progress.

**Comment by maggie-wang-bbt** [comment]
The extension is approved and published on Chrome Web Store: https://chrome.google.com/webstore/detail/metamask-for-cmt/hmiddckbbijmdkamphkgkelnjjdkicck.
